### ISSUE TITLE
Не работает присоединение по приглашению в личку

### ISSUE THREAD

**Issue by anatoliyfedorenko** [maddevsio/mad-internship-bot#10]
После того, как человек принимает приглашение в группу в ЛС, бот начинает тупить и походу падает. надо понять почему и пофиксить это.

**Comment by anatoliyfedorenko** [comment]
Кажется ложная тревога. по логам всё работало. Возможно проблемы в сервере были. Если баг повториться, переотрыть

**Comment by anatoliyfedorenko** [comment]
`bot_1  | time="2019-06-26T00:08:18+06:00" level=error msg="Post https://api.telegram.org/botXXXX/sendMessage: net/http: TLS handshake timeout"` seems like this is causing the problem that sometimes bot does not reply back

**Comment by anatoliyfedorenko** [comment]
Проблема в API телеграмма. закрываю

**Comment by nefrace** [comment]
Я правильно понимаю, что в такой ситуации приходится просто ждать, пока API заработает?
