### ISSUE TITLE
Добавить возможность добавлять дедлайн для стажера 

### ISSUE THREAD

**Issue by a-edakin** [maddevsio/mad-internship-bot#27]
### Контекст:
Недавно выдал 10ти стажерам задание, а сейчас у же не помню точно какое было задание и кому я его выдал. И посколько беседы в чате со стажерами идут активно то найти то сообщение с заданием та еще проблема.

### Проблема:
Сложно следить за выданными заданиями для стажеров, так как их сейчас просто дофига. 

### Решение:
Я вижу такой вариант функционала

Добавляем команду` /setTask ` <дата в формате MM:DD HH:mm> <Список ников стажеров через пробле> <Все остальное просто текст сообщения>

Думаю пока будет достаточно если бот просто в указанную дату перешлет сообщение которое было добавленно что бы напомнить ментору то что он ставил какое то задание

**Comment by anatoliyfedorenko** [comment]
@ArgoSkolnik давай просто команда и время а сообщение сам какое хочешь задавай, с тегами стажёров, без тегов и т.д. нормас?

**Comment by a-edakin** [comment]
Да, без проблем) 

Только если что дайвай будет возможность подредачить сообщение типа сделать edit и это обновится в боте)

**Comment by anatoliyfedorenko** [comment]
уже не актуально для этого бота. в слак боте для стажёров такое сделаем
