### ISSUE TITLE
Make messages language consistent

### ISSUE THREAD

**Issue by anatoliyfedorenko** [maddevsio/mad-internship-bot#44]
Sometimes now the messages are displayed in both languages: 

> Стендап принят, но позволь дать советы: 
> - seems like standups does not contain any prolem or blocker. Remember that problems help us grow. No problems == no development. Dont hesitate to report them
> - seems like standups does not contain any questions. Internship is made up of questions, so ask as many as you can!
> - seems like standups does not contain any tags. If you want your mentors to notice you, tag them right away!
> - seems like standups does not contain any links, that means that probably no work was done or no research was conducted. Poor you.
> - seems like standups does is either small or too large. Appropriate size is about 80 - 200 words.
> 

this should be changed to be consistent, meaning if it begins with Russian, it should continue in Russian. Also, this should be covered by tests to prove its working.

**Comment by BekbolotGM** [comment]
Разбираюсь в коде, пока не понимаю как все это работает.
Вопрос от чего зависит язык сообщений бота, как бот определяет когда писать на английком, а когда на русском?

**Comment by teimurjan** [comment]
@BekbolotGM Исходя из `message.From.LanguageCode`. https://github.com/maddevsio/mad-internship-bot/blob/566d66a7a960b09ef6167eb530b612757cd959c0/bot/events.go#L24

**Comment by BekbolotGM** [comment]
Поднял локально бота для тестирования.

**Comment by BekbolotGM** [comment]
Тестирую бота в телеграме, изучаю код. Хочу понять причину, почему бот в некоторых случаях реагирует на изменения только после рестарта.
