### ISSUE TITLE
Проблема с запуском

### ISSUE THREAD

**Issue by kostia28** [maddevsio/mad-internship-bot#74]
Запустил локально на MacOS бота
Он завелся и слушает чат, но на любую команду выкидывает ошибку mysql
```
time="2020-09-15T18:15:23+06:00" level=error msg="JoinStandupers failed" error="sql: no rows in result set" event="{287097546 0xc0001c6a00 <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>}"
time="2020-09-15T18:15:23+06:00" level=error msg="sql: no rows in result set"
time="2020-09-15T18:16:56+06:00" level=warning msg="Unrecognized command" event="{287097547 0xc0000e7680 <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>}"
time="2020-09-15T18:17:06+06:00" level=error msg="Help failed" error="sql: no rows in result set" event="{287097548 0xc0001c6500 <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>}"
time="2020-09-15T18:17:06+06:00" level=error msg="sql: no rows in result set"
```

**Comment by anatoliyfedorenko** [comment]
Разобраться смогу в течение недели

**Comment by kostia28** [comment]
> Разобраться смогу в течение недели

супер)будет отлично
баг кстати репродьюсится и на убунту тоже

**Comment by kostia28** [comment]
@anatoliyfedorenko добрый день. Получилось исправить?

**Comment by anatoliyfedorenko** [comment]
@kostia28 бот делался давно, нуждается в обновлении. Сейчас я посмотрел на проблему и понял, что это не баг, а фича (как всегда, лол). Т.е. чтобы такой ошибки не было, бота нужно сначала запустить, а только потом добавлять в какой-то канал. Тогда всё будет работать изначально. 
![image](https://user-images.githubusercontent.com/8424103/94168977-06ccb680-feb0-11ea-926a-d594c4f23ab6.png)
